version: '3.8'

services:
  nginx:
    image: nginx:1.23.0
    container_name: nginx
    depends_on:
      - react
      - api
    links:
      - react
      - api
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - 80:80
  react:
    image: node:18.4.0
    container_name: react
    working_dir: /projects
    volumes:
      - "./react:/projects"
    ports:
      - 3000:3000
    tty: true
  api:
    image: golang:1.18
    container_name: api
    working_dir: /app
    depends_on:
      - db
    links:
      - db
    volumes:
      - './api:/app'
    ports:
      - 8080:8080
    tty: true
  db:
    image: postgres:14.4
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_INITDB_ARGS="--encoding=UTF8"
    volumes: 
      - './db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql'
    ports:
      - 5432:5432
    tty: true
