version: '3.8'

services:
  nginx:
    image: nginx:1.23.0
    container_name: nginx
    depends_on:
      - react
      - app
    links:
      - react
      - app
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - 80:80
  react:
    image: node:18.4.0
    container_name: react
    working_dir: /projects
    volumes:
      - "./react:/projects"
    tty: true
  app:
    image: golang:1.18
    container_name: app
    working_dir: /app
    depends_on:
      - db
    links:
      - db
    volumes:
      - './app:/app'
    tty: true
  db:
    image: postgres:14.4
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes: 
      - './db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql'
    tty: true
