version: '3.8'

services:
  react:
    image: node:18.4.0
    container_name: react
    working_dir: /projects
    ports:
      - "3000:3000"
    volumes:
      - "./react:/projects"
    tty: true
  app:
    image: golang:1.18
    container_name: app
    working_dir: /app
    depends_on:
      - db
    ports:
      - 8080:8080
    volumes:
      - './app:/app'
    tty: true
  db:
    image: postgres:14.4
    container_name: db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes: 
      - './db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql'
    tty: true
